version: "3.5"
services:
  poker-web:
    image: carlschader/poker-web
    depends_on:
      - poker-go-api
    ports:
      - target: 80
        published: 80
    environment:
    - PORT=80
    - API_URL=http://poker-go-api:8080
    networks:
      - backend
  poker-go-api:
    build:
      context: .
      dockerfile: services/server/Dockerfile
    depends_on:
      - mongo
      - create-ranks
    networks:
      - backend
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=poker
      - RANKS_COLLECTION_NAME=ranks
      - CACHE_COLLECTION_NAME=cache
      - CALCULATION_TIMEOUT=120
    ports:
      - target: 8080
        published: 8080
  create-ranks:
    build:
      context: .
      dockerfile: services/create-ranks/Dockerfile
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=poker
      - RANKS_COLLECTION_NAME=ranks
      - CACHE_COLLECTION_NAME=cache
  mongo:
    image: mongo
    ports:
      - target: 27017
        published: 27017
    networks:
      - backend
    volumes:
      - mongo:/data/db
networks:
  backend:
volumes:
  mongo: