apiVersion: batch/v1
kind: Job
metadata:
  name: poker-create-ranks
spec:
  template:
    spec:
      containers:
      - name: poker-create-ranks
        image: carlschader/poker-create-ranks
        env:
        - name: MONGODB_URI
          value: mongodb://mongo.default.svc.cluster.local:27017
        - name: DB_NAME
          value: poker
        - name: POCKETS_COLLECTION_NAME
          value: pockets
      restartPolicy: Never
  backoffLimit: 1
